### ISSUE TITLE
Broken page for "Manage Application" without any application

### ISSUE THREAD

**Issue by thibaultduponchelle** [mollusc-labs/slapbird#7]
Hi @mollusc-labs, 

First, your APM monitoring solution looks gorgeous :smiley:

One little report:
If one visits [Manage Application](https://www.slapbirdapm.com/dashboard/manage-application) without actually at least one application, he will get the following broken page:

![slapbird-404](https://github.com/user-attachments/assets/e5adcc90-56d4-4db4-b996-1107364e3c79)

**Comment by rawleyfowler** [comment]
Thanks for the report, we'll have that fixed right away.

**Comment by rawleyfowler** [comment]
Note our CI runs nightly so you'll see this patch tomorrow.
